version: '3'

services:
  database:
    image: cassandra
    container_name: cassandra-chat-app
    volumes:
      - ./data:/var/lib/cassandra
    ports:
      - 9042:9042
  
  # chat-server:
  #   build: ./chat-server
  #   container_name: chat-server
  #   ports:
  #     - 8080:8080
  
  # user-api:
  #   build: ./user-api
  #   container_name: user-api
  #   ports:
  #     - 8081:8080
    # maybe put volume but ig not necessary
  