version: '3'

services:
  cassandra-db:
    image: cassandra
    container_name: cassandra-chat-app
    volumes:
      - ./data:/var/lib/cassandra
    ports:
      - 9042:9042
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces"]
      interval: 1s
      timeout: 5s
      retries: 60
  
  chat-server:
    build: 
      context: ./chat-server
      target: dev
    container_name: chat-server
    ports:
      - 8080:8080
    depends_on:
      cassandra-db:
        condition: service_healthy
  
  user-api:
    build: 
      context: ./user-api
      target: dev
    container_name: user-api
    ports:
      - 8081:8080
    depends_on:
      cassandra-db:
        condition: service_healthy

  conversation-api:
    build:
      context: ./conversation-api
      target: dev
    container_name: conversation-api
    ports:
      - 8082:8080
    depends_on:
      cassandra-db:
        condition: service_healthy

    # maybe put volume but ig not necessary
  